### ISSUE TITLE
'mtrand.pyx': File not found

### ISSUE THREAD

**Issue by mhkefayati** [danielkunin/Message-in-a-Bottle#1]
Hi, trying to run your codes I catch an exception:" Unable to open 'mtrand.pyx': File not found "
on Y = np.random.choice(k, size=m, p=pi) in : perceptron_test>sample_gaussian.
Any idea?

**Comment by danielkunin** [comment]
Not totally sure.  Could be something when size = 0?  Or maybe an issue with your numpy library? Sorry haven't looked at this code in a while.

**Comment by mhkefayati** [comment]
Just reinstalled numpy and updated to numpy-1.15.2, I still catch the exception. Also, the size seems to be non-zero.
Thanks anyway.

**Comment by mhkefayati** [comment]
I finally got around it, the problem was : 'float' object cannot be interpreted as an integer.
and casting the argument m/2 to int solved my problem.

**Comment by danielkunin** [comment]
Great!  Glad you fixed it.  Sorry about that!

**Comment by yusuf0x73** [comment]
The probabilities was the problem in my case, they should sum up to 1, inshaAllah.
